POST http://localhost:3001/users/register
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "password": "john123"
}

###
PATCH http://localhost:3001/users/me
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "password": "john"
}

###
POST http://localhost:3001/users
content-type: application/json

{
    "firstName": "John3",
    "lastName": "Doe3",
    "email": "johndoe3@gmail.com",
    "password": "john1233"
}


###
DELETE http://localhost:3001/users/fa507051-e12d-499b-847d-619f25da4843

###
POST http://localhost:3001/users/login
content-type: application/json

{
    "email": "bahriddin@gmail.com",
    "password": "bahriddin"
}

###
POST http://localhost:3001/users/login
content-type: application/json

{
    "email": "sammiac@gmail.com",
    "password": "sammi123"
}

###
POST http://localhost:3001/users/login
content-type: application/json

{
    "email": "johndoe@gmail.com",
    "password": "john123"
}